/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ch.rasc.otodo.db.tables.AppSession;
import ch.rasc.otodo.db.tables.AppUser;
import ch.rasc.otodo.db.tables.Todo;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

  private static final long serialVersionUID = 672558943;

  /**
   * The reference instance of <code></code>
   */
  public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

  /**
   * The table <code>app_session</code>.
   */
  public final AppSession APP_SESSION = ch.rasc.otodo.db.tables.AppSession.APP_SESSION;

  /**
   * The table <code>app_user</code>.
   */
  public final AppUser APP_USER = ch.rasc.otodo.db.tables.AppUser.APP_USER;

  /**
   * The table <code>todo</code>.
   */
  public final Todo TODO = ch.rasc.otodo.db.tables.Todo.TODO;

  /**
   * No further instances allowed
   */
  private DefaultSchema() {
    super("", null);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    List result = new ArrayList();
    result.addAll(getTables0());
    return result;
  }

  private final List<Table<?>> getTables0() {
    return Arrays.<Table<?>>asList(AppSession.APP_SESSION, AppUser.APP_USER, Todo.TODO);
  }
}
