/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db;

import ch.rasc.otodo.db.tables.AppSession;
import ch.rasc.otodo.db.tables.AppUser;
import ch.rasc.otodo.db.tables.Todo;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>DEFAULT_SCHEMA</code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * The table <code>app_session</code>.
	 */
	public final AppSession APP_SESSION = AppSession.APP_SESSION;

	/**
	 * The table <code>app_user</code>.
	 */
	public final AppUser APP_USER = AppUser.APP_USER;

	/**
	 * The table <code>todo</code>.
	 */
	public final Todo TODO = Todo.TODO;

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("", null);
	}

	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.asList(AppSession.APP_SESSION, AppUser.APP_USER, Todo.TODO);
	}

}
