/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db;

import ch.rasc.otodo.db.tables.AppSession;
import ch.rasc.otodo.db.tables.Todo;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

	// -------------------------------------------------------------------------
	// INDEX definitions
	// -------------------------------------------------------------------------

	public static final Index APP_SESSION_APP_USER_ID = Internal.createIndex(DSL.name("app_user_id"),
			AppSession.APP_SESSION, new OrderField[] { AppSession.APP_SESSION.APP_USER_ID }, false);

	public static final Index TODO_APP_USER_ID = Internal.createIndex(DSL.name("app_user_id"), Todo.TODO,
			new OrderField[] { Todo.TODO.APP_USER_ID }, false);

}
