/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ch.rasc.otodo.db.tables.AppSession;
import ch.rasc.otodo.db.tables.AppUser;
import ch.rasc.otodo.db.tables.Todo;

/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index APP_SESSION_APP_USER_ID = Indexes0.APP_SESSION_APP_USER_ID;
  public static final Index APP_SESSION_PRIMARY = Indexes0.APP_SESSION_PRIMARY;
  public static final Index APP_USER_EMAIL = Indexes0.APP_USER_EMAIL;
  public static final Index APP_USER_PRIMARY = Indexes0.APP_USER_PRIMARY;
  public static final Index TODO_APP_USER_ID = Indexes0.TODO_APP_USER_ID;
  public static final Index TODO_PRIMARY = Indexes0.TODO_PRIMARY;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Indexes0 {
    public static Index APP_SESSION_APP_USER_ID = Internal.createIndex("app_user_id",
        AppSession.APP_SESSION, new OrderField[] { AppSession.APP_SESSION.APP_USER_ID },
        false);
    public static Index APP_SESSION_PRIMARY = Internal.createIndex("PRIMARY",
        AppSession.APP_SESSION, new OrderField[] { AppSession.APP_SESSION.ID }, true);
    public static Index APP_USER_EMAIL = Internal.createIndex("email", AppUser.APP_USER,
        new OrderField[] { AppUser.APP_USER.EMAIL }, true);
    public static Index APP_USER_PRIMARY = Internal.createIndex("PRIMARY",
        AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.ID }, true);
    public static Index TODO_APP_USER_ID = Internal.createIndex("app_user_id", Todo.TODO,
        new OrderField[] { Todo.TODO.APP_USER_ID }, false);
    public static Index TODO_PRIMARY = Internal.createIndex("PRIMARY", Todo.TODO,
        new OrderField[] { Todo.TODO.ID }, true);
  }
}
