/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db;

import ch.rasc.otodo.db.tables.AppSession;
import ch.rasc.otodo.db.tables.AppUser;
import ch.rasc.otodo.db.tables.Todo;
import ch.rasc.otodo.db.tables.records.AppSessionRecord;
import ch.rasc.otodo.db.tables.records.AppUserRecord;
import ch.rasc.otodo.db.tables.records.TodoRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the default
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AppSessionRecord> KEY_APP_SESSION_PRIMARY = Internal.createUniqueKey(
			AppSession.APP_SESSION, DSL.name("KEY_app_session_PRIMARY"), new TableField[] { AppSession.APP_SESSION.ID },
			true);

	public static final UniqueKey<AppUserRecord> KEY_APP_USER_EMAIL = Internal.createUniqueKey(AppUser.APP_USER,
			DSL.name("KEY_app_user_email"), new TableField[] { AppUser.APP_USER.EMAIL }, true);

	public static final UniqueKey<AppUserRecord> KEY_APP_USER_PRIMARY = Internal.createUniqueKey(AppUser.APP_USER,
			DSL.name("KEY_app_user_PRIMARY"), new TableField[] { AppUser.APP_USER.ID }, true);

	public static final UniqueKey<TodoRecord> KEY_TODO_PRIMARY = Internal.createUniqueKey(Todo.TODO,
			DSL.name("KEY_todo_PRIMARY"), new TableField[] { Todo.TODO.ID }, true);

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AppSessionRecord, AppUserRecord> APP_SESSION_IBFK_1 = Internal.createForeignKey(
			AppSession.APP_SESSION, DSL.name("app_session_ibfk_1"),
			new TableField[] { AppSession.APP_SESSION.APP_USER_ID }, Keys.KEY_APP_USER_PRIMARY,
			new TableField[] { AppUser.APP_USER.ID }, true);

	public static final ForeignKey<TodoRecord, AppUserRecord> TODO_IBFK_1 = Internal.createForeignKey(Todo.TODO,
			DSL.name("todo_ibfk_1"), new TableField[] { Todo.TODO.APP_USER_ID }, Keys.KEY_APP_USER_PRIMARY,
			new TableField[] { AppUser.APP_USER.ID }, true);

}
