/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db;

import ch.rasc.otodo.db.tables.AppSession;
import ch.rasc.otodo.db.tables.AppUser;
import ch.rasc.otodo.db.tables.Todo;

/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

	/**
	 * The table <code>app_session</code>.
	 */
	public static final AppSession APP_SESSION = AppSession.APP_SESSION;

	/**
	 * The table <code>app_user</code>.
	 */
	public static final AppUser APP_USER = AppUser.APP_USER;

	/**
	 * The table <code>todo</code>.
	 */
	public static final Todo TODO = Todo.TODO;

}
