/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db;


import ch.rasc.otodo.db.tables.AppSession;
import ch.rasc.otodo.db.tables.AppUser;
import ch.rasc.otodo.db.tables.Todo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>app_session</code>.
     */
    public static final AppSession APP_SESSION = ch.rasc.otodo.db.tables.AppSession.APP_SESSION;

    /**
     * The table <code>app_user</code>.
     */
    public static final AppUser APP_USER = ch.rasc.otodo.db.tables.AppUser.APP_USER;

    /**
     * The table <code>todo</code>.
     */
    public static final Todo TODO = ch.rasc.otodo.db.tables.Todo.TODO;
}
