services:
  otodo_db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: otodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - "2500:2500"
      - "9000:9000"
