/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db.tables;

import ch.rasc.otodo.db.DefaultSchema;
import ch.rasc.otodo.db.Indexes;
import ch.rasc.otodo.db.Keys;
import ch.rasc.otodo.db.tables.AppUser.AppUserPath;
import ch.rasc.otodo.db.tables.records.AppSessionRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppSession extends TableImpl<AppSessionRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>app_session</code>
	 */
	public static final AppSession APP_SESSION = new AppSession();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppSessionRecord> getRecordType() {
		return AppSessionRecord.class;
	}

	/**
	 * The column <code>app_session.id</code>.
	 */
	public final TableField<AppSessionRecord, String> ID = createField(DSL.name("id"),
			SQLDataType.CHAR(35).nullable(false), this, "");

	/**
	 * The column <code>app_session.app_user_id</code>.
	 */
	public final TableField<AppSessionRecord, Long> APP_USER_ID = createField(DSL.name("app_user_id"),
			SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>app_session.last_access</code>.
	 */
	public final TableField<AppSessionRecord, LocalDateTime> LAST_ACCESS = createField(DSL.name("last_access"),
			SQLDataType.LOCALDATETIME(0)
				.nullable(false)
				.defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)),
			this, "");

	/**
	 * The column <code>app_session.ip</code>.
	 */
	public final TableField<AppSessionRecord, String> IP = createField(DSL.name("ip"),
			SQLDataType.VARCHAR(39).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>app_session.user_agent</code>.
	 */
	public final TableField<AppSessionRecord, String> USER_AGENT = createField(DSL.name("user_agent"),
			SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	private AppSession(Name alias, Table<AppSessionRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private AppSession(Name alias, Table<AppSessionRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>app_session</code> table reference
	 */
	public AppSession(String alias) {
		this(DSL.name(alias), APP_SESSION);
	}

	/**
	 * Create an aliased <code>app_session</code> table reference
	 */
	public AppSession(Name alias) {
		this(alias, APP_SESSION);
	}

	/**
	 * Create a <code>app_session</code> table reference
	 */
	public AppSession() {
		this(DSL.name("app_session"), null);
	}

	public <O extends Record> AppSession(Table<O> path, ForeignKey<O, AppSessionRecord> childPath,
			InverseForeignKey<O, AppSessionRecord> parentPath) {
		super(path, childPath, parentPath, APP_SESSION);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class AppSessionPath extends AppSession implements Path<AppSessionRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> AppSessionPath(Table<O> path, ForeignKey<O, AppSessionRecord> childPath,
				InverseForeignKey<O, AppSessionRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private AppSessionPath(Name alias, Table<AppSessionRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public AppSessionPath as(String alias) {
			return new AppSessionPath(DSL.name(alias), this);
		}

		@Override
		public AppSessionPath as(Name alias) {
			return new AppSessionPath(alias, this);
		}

		@Override
		public AppSessionPath as(Table<?> alias) {
			return new AppSessionPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.APP_SESSION_APP_USER_ID);
	}

	@Override
	public UniqueKey<AppSessionRecord> getPrimaryKey() {
		return Keys.KEY_APP_SESSION_PRIMARY;
	}

	@Override
	public List<ForeignKey<AppSessionRecord, ?>> getReferences() {
		return Arrays.asList(Keys.APP_SESSION_IBFK_1);
	}

	private transient AppUserPath _appUser;

	/**
	 * Get the implicit join path to the <code>app_user</code> table.
	 */
	public AppUserPath appUser() {
		if (_appUser == null)
			_appUser = new AppUserPath(this, Keys.APP_SESSION_IBFK_1, null);

		return _appUser;
	}

	@Override
	public AppSession as(String alias) {
		return new AppSession(DSL.name(alias), this);
	}

	@Override
	public AppSession as(Name alias) {
		return new AppSession(alias, this);
	}

	@Override
	public AppSession as(Table<?> alias) {
		return new AppSession(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public AppSession rename(String name) {
		return new AppSession(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public AppSession rename(Name name) {
		return new AppSession(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public AppSession rename(Table<?> name) {
		return new AppSession(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppSession where(Condition condition) {
		return new AppSession(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppSession where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppSession where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppSession where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppSession where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppSession where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppSession where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppSession where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppSession whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppSession whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
