/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db.tables;

import ch.rasc.otodo.db.DefaultSchema;
import ch.rasc.otodo.db.Keys;
import ch.rasc.otodo.db.tables.AppSession.AppSessionPath;
import ch.rasc.otodo.db.tables.Todo.TodoPath;
import ch.rasc.otodo.db.tables.records.AppUserRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUser extends TableImpl<AppUserRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>app_user</code>
	 */
	public static final AppUser APP_USER = new AppUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppUserRecord> getRecordType() {
		return AppUserRecord.class;
	}

	/**
	 * The column <code>app_user.id</code>.
	 */
	public final TableField<AppUserRecord, Long> ID = createField(DSL.name("id"),
			SQLDataType.BIGINT.nullable(false).identity(true), this, "");

	/**
	 * The column <code>app_user.email</code>.
	 */
	public final TableField<AppUserRecord, String> EMAIL = createField(DSL.name("email"),
			SQLDataType.VARCHAR(255).nullable(false), this, "");

	/**
	 * The column <code>app_user.email_new</code>.
	 */
	public final TableField<AppUserRecord, String> EMAIL_NEW = createField(DSL.name("email_new"),
			SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>app_user.password_hash</code>.
	 */
	public final TableField<AppUserRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"),
			SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>app_user.authority</code>.
	 */
	public final TableField<AppUserRecord, String> AUTHORITY = createField(DSL.name("authority"),
			SQLDataType.VARCHAR(10).nullable(false), this, "");

	/**
	 * The column <code>app_user.enabled</code>.
	 */
	public final TableField<AppUserRecord, Boolean> ENABLED = createField(DSL.name("enabled"),
			SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>app_user.expired</code>.
	 */
	public final TableField<AppUserRecord, LocalDateTime> EXPIRED = createField(DSL.name("expired"),
			SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

	/**
	 * The column <code>app_user.last_access</code>.
	 */
	public final TableField<AppUserRecord, LocalDateTime> LAST_ACCESS = createField(DSL.name("last_access"),
			SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

	/**
	 * The column <code>app_user.confirmation_token</code>.
	 */
	public final TableField<AppUserRecord, String> CONFIRMATION_TOKEN = createField(DSL.name("confirmation_token"),
			SQLDataType.CHAR(35).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CHAR)), this, "");

	/**
	 * The column <code>app_user.confirmation_token_created</code>.
	 */
	public final TableField<AppUserRecord, LocalDateTime> CONFIRMATION_TOKEN_CREATED = createField(
			DSL.name("confirmation_token_created"),
			SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

	/**
	 * The column <code>app_user.password_reset_token</code>.
	 */
	public final TableField<AppUserRecord, String> PASSWORD_RESET_TOKEN = createField(DSL.name("password_reset_token"),
			SQLDataType.CHAR(35).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CHAR)), this, "");

	/**
	 * The column <code>app_user.password_reset_token_created</code>.
	 */
	public final TableField<AppUserRecord, LocalDateTime> PASSWORD_RESET_TOKEN_CREATED = createField(
			DSL.name("password_reset_token_created"),
			SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

	private AppUser(Name alias, Table<AppUserRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private AppUser(Name alias, Table<AppUserRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>app_user</code> table reference
	 */
	public AppUser(String alias) {
		this(DSL.name(alias), APP_USER);
	}

	/**
	 * Create an aliased <code>app_user</code> table reference
	 */
	public AppUser(Name alias) {
		this(alias, APP_USER);
	}

	/**
	 * Create a <code>app_user</code> table reference
	 */
	public AppUser() {
		this(DSL.name("app_user"), null);
	}

	public <O extends Record> AppUser(Table<O> path, ForeignKey<O, AppUserRecord> childPath,
			InverseForeignKey<O, AppUserRecord> parentPath) {
		super(path, childPath, parentPath, APP_USER);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class AppUserPath extends AppUser implements Path<AppUserRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> AppUserPath(Table<O> path, ForeignKey<O, AppUserRecord> childPath,
				InverseForeignKey<O, AppUserRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private AppUserPath(Name alias, Table<AppUserRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public AppUserPath as(String alias) {
			return new AppUserPath(DSL.name(alias), this);
		}

		@Override
		public AppUserPath as(Name alias) {
			return new AppUserPath(alias, this);
		}

		@Override
		public AppUserPath as(Table<?> alias) {
			return new AppUserPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<AppUserRecord, Long> getIdentity() {
		return (Identity<AppUserRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<AppUserRecord> getPrimaryKey() {
		return Keys.KEY_APP_USER_PRIMARY;
	}

	@Override
	public List<UniqueKey<AppUserRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_APP_USER_EMAIL);
	}

	private transient AppSessionPath _appSession;

	/**
	 * Get the implicit to-many join path to the <code>app_session</code> table
	 */
	public AppSessionPath appSession() {
		if (_appSession == null)
			_appSession = new AppSessionPath(this, null, Keys.APP_SESSION_IBFK_1.getInverseKey());

		return _appSession;
	}

	private transient TodoPath _todo;

	/**
	 * Get the implicit to-many join path to the <code>todo</code> table
	 */
	public TodoPath todo() {
		if (_todo == null)
			_todo = new TodoPath(this, null, Keys.TODO_IBFK_1.getInverseKey());

		return _todo;
	}

	@Override
	public List<Check<AppUserRecord>> getChecks() {
		return Arrays
			.asList(Internal.createCheck(this, DSL.name("CONSTRAINT_1"), "`authority` in ('USER','ADMIN')", true));
	}

	@Override
	public AppUser as(String alias) {
		return new AppUser(DSL.name(alias), this);
	}

	@Override
	public AppUser as(Name alias) {
		return new AppUser(alias, this);
	}

	@Override
	public AppUser as(Table<?> alias) {
		return new AppUser(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public AppUser rename(String name) {
		return new AppUser(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public AppUser rename(Name name) {
		return new AppUser(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public AppUser rename(Table<?> name) {
		return new AppUser(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppUser where(Condition condition) {
		return new AppUser(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppUser where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppUser where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppUser where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppUser where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppUser where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppUser where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public AppUser where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppUser whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public AppUser whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
