/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db.tables;

import ch.rasc.otodo.db.DefaultSchema;
import ch.rasc.otodo.db.Indexes;
import ch.rasc.otodo.db.Keys;
import ch.rasc.otodo.db.tables.AppUser.AppUserPath;
import ch.rasc.otodo.db.tables.records.TodoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Todo extends TableImpl<TodoRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>todo</code>
	 */
	public static final Todo TODO = new Todo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TodoRecord> getRecordType() {
		return TodoRecord.class;
	}

	/**
	 * The column <code>todo.id</code>.
	 */
	public final TableField<TodoRecord, Long> ID = createField(DSL.name("id"),
			SQLDataType.BIGINT.nullable(false).identity(true), this, "");

	/**
	 * The column <code>todo.subject</code>.
	 */
	public final TableField<TodoRecord, String> SUBJECT = createField(DSL.name("subject"),
			SQLDataType.VARCHAR(255).nullable(false), this, "");

	/**
	 * The column <code>todo.description</code>.
	 */
	public final TableField<TodoRecord, String> DESCRIPTION = createField(DSL.name("description"),
			SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>todo.app_user_id</code>.
	 */
	public final TableField<TodoRecord, Long> APP_USER_ID = createField(DSL.name("app_user_id"),
			SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>todo.updated</code>.
	 */
	public final TableField<TodoRecord, LocalDateTime> UPDATED = createField(DSL.name("updated"),
			SQLDataType.LOCALDATETIME(0)
				.nullable(false)
				.defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)),
			this, "");

	private Todo(Name alias, Table<TodoRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Todo(Name alias, Table<TodoRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>todo</code> table reference
	 */
	public Todo(String alias) {
		this(DSL.name(alias), TODO);
	}

	/**
	 * Create an aliased <code>todo</code> table reference
	 */
	public Todo(Name alias) {
		this(alias, TODO);
	}

	/**
	 * Create a <code>todo</code> table reference
	 */
	public Todo() {
		this(DSL.name("todo"), null);
	}

	public <O extends Record> Todo(Table<O> path, ForeignKey<O, TodoRecord> childPath,
			InverseForeignKey<O, TodoRecord> parentPath) {
		super(path, childPath, parentPath, TODO);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TodoPath extends Todo implements Path<TodoRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> TodoPath(Table<O> path, ForeignKey<O, TodoRecord> childPath,
				InverseForeignKey<O, TodoRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private TodoPath(Name alias, Table<TodoRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TodoPath as(String alias) {
			return new TodoPath(DSL.name(alias), this);
		}

		@Override
		public TodoPath as(Name alias) {
			return new TodoPath(alias, this);
		}

		@Override
		public TodoPath as(Table<?> alias) {
			return new TodoPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.TODO_APP_USER_ID);
	}

	@Override
	public Identity<TodoRecord, Long> getIdentity() {
		return (Identity<TodoRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<TodoRecord> getPrimaryKey() {
		return Keys.KEY_TODO_PRIMARY;
	}

	@Override
	public List<ForeignKey<TodoRecord, ?>> getReferences() {
		return Arrays.asList(Keys.TODO_IBFK_1);
	}

	private transient AppUserPath _appUser;

	/**
	 * Get the implicit join path to the <code>app_user</code> table.
	 */
	public AppUserPath appUser() {
		if (_appUser == null)
			_appUser = new AppUserPath(this, Keys.TODO_IBFK_1, null);

		return _appUser;
	}

	@Override
	public Todo as(String alias) {
		return new Todo(DSL.name(alias), this);
	}

	@Override
	public Todo as(Name alias) {
		return new Todo(alias, this);
	}

	@Override
	public Todo as(Table<?> alias) {
		return new Todo(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Todo rename(String name) {
		return new Todo(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Todo rename(Name name) {
		return new Todo(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Todo rename(Table<?> name) {
		return new Todo(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Todo where(Condition condition) {
		return new Todo(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Todo where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Todo where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Todo where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Todo where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Todo where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Todo where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Todo where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Todo whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Todo whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
