/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db.tables.records;

import ch.rasc.otodo.db.tables.AppSession;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppSessionRecord extends UpdatableRecordImpl<AppSessionRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>app_session.id</code>.
	 */
	public void setId(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>app_session.id</code>.
	 */
	public String getId() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>app_session.app_user_id</code>.
	 */
	public void setAppUserId(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>app_session.app_user_id</code>.
	 */
	public Long getAppUserId() {
		return (Long) get(1);
	}

	/**
	 * Setter for <code>app_session.last_access</code>.
	 */
	public void setLastAccess(LocalDateTime value) {
		set(2, value);
	}

	/**
	 * Getter for <code>app_session.last_access</code>.
	 */
	public LocalDateTime getLastAccess() {
		return (LocalDateTime) get(2);
	}

	/**
	 * Setter for <code>app_session.ip</code>.
	 */
	public void setIp(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>app_session.ip</code>.
	 */
	public String getIp() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>app_session.user_agent</code>.
	 */
	public void setUserAgent(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>app_session.user_agent</code>.
	 */
	public String getUserAgent() {
		return (String) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppSessionRecord
	 */
	public AppSessionRecord() {
		super(AppSession.APP_SESSION);
	}

	/**
	 * Create a detached, initialised AppSessionRecord
	 */
	public AppSessionRecord(String id, Long appUserId, LocalDateTime lastAccess, String ip, String userAgent) {
		super(AppSession.APP_SESSION);

		setId(id);
		setAppUserId(appUserId);
		setLastAccess(lastAccess);
		setIp(ip);
		setUserAgent(userAgent);
		resetChangedOnNotNull();
	}

}
