/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db.tables.records;

import ch.rasc.otodo.db.tables.AppUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>app_user.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>app_user.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>app_user.email</code>.
	 */
	public void setEmail(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>app_user.email</code>.
	 */
	public String getEmail() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>app_user.email_new</code>.
	 */
	public void setEmailNew(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>app_user.email_new</code>.
	 */
	public String getEmailNew() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>app_user.password_hash</code>.
	 */
	public void setPasswordHash(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>app_user.password_hash</code>.
	 */
	public String getPasswordHash() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>app_user.authority</code>.
	 */
	public void setAuthority(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>app_user.authority</code>.
	 */
	public String getAuthority() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>app_user.enabled</code>.
	 */
	public void setEnabled(Boolean value) {
		set(5, value);
	}

	/**
	 * Getter for <code>app_user.enabled</code>.
	 */
	public Boolean getEnabled() {
		return (Boolean) get(5);
	}

	/**
	 * Setter for <code>app_user.expired</code>.
	 */
	public void setExpired(LocalDateTime value) {
		set(6, value);
	}

	/**
	 * Getter for <code>app_user.expired</code>.
	 */
	public LocalDateTime getExpired() {
		return (LocalDateTime) get(6);
	}

	/**
	 * Setter for <code>app_user.last_access</code>.
	 */
	public void setLastAccess(LocalDateTime value) {
		set(7, value);
	}

	/**
	 * Getter for <code>app_user.last_access</code>.
	 */
	public LocalDateTime getLastAccess() {
		return (LocalDateTime) get(7);
	}

	/**
	 * Setter for <code>app_user.confirmation_token</code>.
	 */
	public void setConfirmationToken(String value) {
		set(8, value);
	}

	/**
	 * Getter for <code>app_user.confirmation_token</code>.
	 */
	public String getConfirmationToken() {
		return (String) get(8);
	}

	/**
	 * Setter for <code>app_user.confirmation_token_created</code>.
	 */
	public void setConfirmationTokenCreated(LocalDateTime value) {
		set(9, value);
	}

	/**
	 * Getter for <code>app_user.confirmation_token_created</code>.
	 */
	public LocalDateTime getConfirmationTokenCreated() {
		return (LocalDateTime) get(9);
	}

	/**
	 * Setter for <code>app_user.password_reset_token</code>.
	 */
	public void setPasswordResetToken(String value) {
		set(10, value);
	}

	/**
	 * Getter for <code>app_user.password_reset_token</code>.
	 */
	public String getPasswordResetToken() {
		return (String) get(10);
	}

	/**
	 * Setter for <code>app_user.password_reset_token_created</code>.
	 */
	public void setPasswordResetTokenCreated(LocalDateTime value) {
		set(11, value);
	}

	/**
	 * Getter for <code>app_user.password_reset_token_created</code>.
	 */
	public LocalDateTime getPasswordResetTokenCreated() {
		return (LocalDateTime) get(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppUserRecord
	 */
	public AppUserRecord() {
		super(AppUser.APP_USER);
	}

	/**
	 * Create a detached, initialised AppUserRecord
	 */
	public AppUserRecord(Long id, String email, String emailNew, String passwordHash, String authority, Boolean enabled,
			LocalDateTime expired, LocalDateTime lastAccess, String confirmationToken,
			LocalDateTime confirmationTokenCreated, String passwordResetToken,
			LocalDateTime passwordResetTokenCreated) {
		super(AppUser.APP_USER);

		setId(id);
		setEmail(email);
		setEmailNew(emailNew);
		setPasswordHash(passwordHash);
		setAuthority(authority);
		setEnabled(enabled);
		setExpired(expired);
		setLastAccess(lastAccess);
		setConfirmationToken(confirmationToken);
		setConfirmationTokenCreated(confirmationTokenCreated);
		setPasswordResetToken(passwordResetToken);
		setPasswordResetTokenCreated(passwordResetTokenCreated);
		resetChangedOnNotNull();
	}

}
