/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db.tables.records;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.otodo.db.tables.AppUser;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> implements
    Record14<Long, String, String, String, String, Boolean, LocalDateTime, Integer, LocalDateTime, LocalDateTime, String, LocalDateTime, String, LocalDateTime> {

  private static final long serialVersionUID = -1973731891;

  /**
   * Setter for <code>app_user.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>app_user.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>app_user.email</code>.
   */
  public void setEmail(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>app_user.email</code>.
   */
  public String getEmail() {
    return (String) get(1);
  }

  /**
   * Setter for <code>app_user.email_new</code>.
   */
  public void setEmailNew(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>app_user.email_new</code>.
   */
  public String getEmailNew() {
    return (String) get(2);
  }

  /**
   * Setter for <code>app_user.password_hash</code>.
   */
  public void setPasswordHash(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>app_user.password_hash</code>.
   */
  public String getPasswordHash() {
    return (String) get(3);
  }

  /**
   * Setter for <code>app_user.authority</code>.
   */
  public void setAuthority(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>app_user.authority</code>.
   */
  public String getAuthority() {
    return (String) get(4);
  }

  /**
   * Setter for <code>app_user.enabled</code>.
   */
  public void setEnabled(Boolean value) {
    set(5, value);
  }

  /**
   * Getter for <code>app_user.enabled</code>.
   */
  public Boolean getEnabled() {
    return (Boolean) get(5);
  }

  /**
   * Setter for <code>app_user.expired</code>.
   */
  public void setExpired(LocalDateTime value) {
    set(6, value);
  }

  /**
   * Getter for <code>app_user.expired</code>.
   */
  public LocalDateTime getExpired() {
    return (LocalDateTime) get(6);
  }

  /**
   * Setter for <code>app_user.failed_logins</code>.
   */
  public void setFailedLogins(Integer value) {
    set(7, value);
  }

  /**
   * Getter for <code>app_user.failed_logins</code>.
   */
  public Integer getFailedLogins() {
    return (Integer) get(7);
  }

  /**
   * Setter for <code>app_user.locked_out</code>.
   */
  public void setLockedOut(LocalDateTime value) {
    set(8, value);
  }

  /**
   * Getter for <code>app_user.locked_out</code>.
   */
  public LocalDateTime getLockedOut() {
    return (LocalDateTime) get(8);
  }

  /**
   * Setter for <code>app_user.last_access</code>.
   */
  public void setLastAccess(LocalDateTime value) {
    set(9, value);
  }

  /**
   * Getter for <code>app_user.last_access</code>.
   */
  public LocalDateTime getLastAccess() {
    return (LocalDateTime) get(9);
  }

  /**
   * Setter for <code>app_user.confirmation_token</code>.
   */
  public void setConfirmationToken(String value) {
    set(10, value);
  }

  /**
   * Getter for <code>app_user.confirmation_token</code>.
   */
  public String getConfirmationToken() {
    return (String) get(10);
  }

  /**
   * Setter for <code>app_user.confirmation_token_created</code>.
   */
  public void setConfirmationTokenCreated(LocalDateTime value) {
    set(11, value);
  }

  /**
   * Getter for <code>app_user.confirmation_token_created</code>.
   */
  public LocalDateTime getConfirmationTokenCreated() {
    return (LocalDateTime) get(11);
  }

  /**
   * Setter for <code>app_user.password_reset_token</code>.
   */
  public void setPasswordResetToken(String value) {
    set(12, value);
  }

  /**
   * Getter for <code>app_user.password_reset_token</code>.
   */
  public String getPasswordResetToken() {
    return (String) get(12);
  }

  /**
   * Setter for <code>app_user.password_reset_token_created</code>.
   */
  public void setPasswordResetTokenCreated(LocalDateTime value) {
    set(13, value);
  }

  /**
   * Getter for <code>app_user.password_reset_token_created</code>.
   */
  public LocalDateTime getPasswordResetTokenCreated() {
    return (LocalDateTime) get(13);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record14 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row14<Long, String, String, String, String, Boolean, LocalDateTime, Integer, LocalDateTime, LocalDateTime, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
    return (Row14) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row14<Long, String, String, String, String, Boolean, LocalDateTime, Integer, LocalDateTime, LocalDateTime, String, LocalDateTime, String, LocalDateTime> valuesRow() {
    return (Row14) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Long> field1() {
    return AppUser.APP_USER.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return AppUser.APP_USER.EMAIL;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return AppUser.APP_USER.EMAIL_NEW;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return AppUser.APP_USER.PASSWORD_HASH;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field5() {
    return AppUser.APP_USER.AUTHORITY;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Boolean> field6() {
    return AppUser.APP_USER.ENABLED;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field7() {
    return AppUser.APP_USER.EXPIRED;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field8() {
    return AppUser.APP_USER.FAILED_LOGINS;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field9() {
    return AppUser.APP_USER.LOCKED_OUT;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field10() {
    return AppUser.APP_USER.LAST_ACCESS;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field11() {
    return AppUser.APP_USER.CONFIRMATION_TOKEN;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field12() {
    return AppUser.APP_USER.CONFIRMATION_TOKEN_CREATED;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field13() {
    return AppUser.APP_USER.PASSWORD_RESET_TOKEN;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<LocalDateTime> field14() {
    return AppUser.APP_USER.PASSWORD_RESET_TOKEN_CREATED;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getEmail();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getEmailNew();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getPasswordHash();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component5() {
    return getAuthority();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Boolean component6() {
    return getEnabled();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component7() {
    return getExpired();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component8() {
    return getFailedLogins();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component9() {
    return getLockedOut();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component10() {
    return getLastAccess();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component11() {
    return getConfirmationToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component12() {
    return getConfirmationTokenCreated();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component13() {
    return getPasswordResetToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime component14() {
    return getPasswordResetTokenCreated();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Long value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getEmail();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getEmailNew();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getPasswordHash();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value5() {
    return getAuthority();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Boolean value6() {
    return getEnabled();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value7() {
    return getExpired();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value8() {
    return getFailedLogins();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value9() {
    return getLockedOut();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value10() {
    return getLastAccess();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value11() {
    return getConfirmationToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value12() {
    return getConfirmationTokenCreated();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value13() {
    return getPasswordResetToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public LocalDateTime value14() {
    return getPasswordResetTokenCreated();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value1(Long value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value2(String value) {
    setEmail(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value3(String value) {
    setEmailNew(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value4(String value) {
    setPasswordHash(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value5(String value) {
    setAuthority(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value6(Boolean value) {
    setEnabled(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value7(LocalDateTime value) {
    setExpired(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value8(Integer value) {
    setFailedLogins(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value9(LocalDateTime value) {
    setLockedOut(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value10(LocalDateTime value) {
    setLastAccess(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value11(String value) {
    setConfirmationToken(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value12(LocalDateTime value) {
    setConfirmationTokenCreated(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value13(String value) {
    setPasswordResetToken(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord value14(LocalDateTime value) {
    setPasswordResetTokenCreated(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AppUserRecord values(Long value1, String value2, String value3, String value4,
      String value5, Boolean value6, LocalDateTime value7, Integer value8,
      LocalDateTime value9, LocalDateTime value10, String value11, LocalDateTime value12,
      String value13, LocalDateTime value14) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    value14(value14);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached AppUserRecord
   */
  public AppUserRecord() {
    super(AppUser.APP_USER);
  }

  /**
   * Create a detached, initialised AppUserRecord
   */
  public AppUserRecord(Long id, String email, String emailNew, String passwordHash,
      String authority, Boolean enabled, LocalDateTime expired, Integer failedLogins,
      LocalDateTime lockedOut, LocalDateTime lastAccess, String confirmationToken,
      LocalDateTime confirmationTokenCreated, String passwordResetToken,
      LocalDateTime passwordResetTokenCreated) {
    super(AppUser.APP_USER);

    set(0, id);
    set(1, email);
    set(2, emailNew);
    set(3, passwordHash);
    set(4, authority);
    set(5, enabled);
    set(6, expired);
    set(7, failedLogins);
    set(8, lockedOut);
    set(9, lastAccess);
    set(10, confirmationToken);
    set(11, confirmationTokenCreated);
    set(12, passwordResetToken);
    set(13, passwordResetTokenCreated);
  }
}
