/*
 * This file is generated by jOOQ.
 */
package ch.rasc.otodo.db.tables.records;

import ch.rasc.otodo.db.tables.Todo;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TodoRecord extends UpdatableRecordImpl<TodoRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>todo.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>todo.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>todo.subject</code>.
	 */
	public void setSubject(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>todo.subject</code>.
	 */
	public String getSubject() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>todo.description</code>.
	 */
	public void setDescription(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>todo.description</code>.
	 */
	public String getDescription() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>todo.app_user_id</code>.
	 */
	public void setAppUserId(Long value) {
		set(3, value);
	}

	/**
	 * Getter for <code>todo.app_user_id</code>.
	 */
	public Long getAppUserId() {
		return (Long) get(3);
	}

	/**
	 * Setter for <code>todo.updated</code>.
	 */
	public void setUpdated(LocalDateTime value) {
		set(4, value);
	}

	/**
	 * Getter for <code>todo.updated</code>.
	 */
	public LocalDateTime getUpdated() {
		return (LocalDateTime) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TodoRecord
	 */
	public TodoRecord() {
		super(Todo.TODO);
	}

	/**
	 * Create a detached, initialised TodoRecord
	 */
	public TodoRecord(Long id, String subject, String description, Long appUserId, LocalDateTime updated) {
		super(Todo.TODO);

		setId(id);
		setSubject(subject);
		setDescription(description);
		setAppUserId(appUserId);
		setUpdated(updated);
		resetChangedOnNotNull();
	}

}
